import type { QuestTemplate, RarityConfig, Rarity, RankConfig, Rank, ShopItem } from './types'

export const BOARD_SIZE = 6
export const REFRESH_COST = 5
export const MAX_ACTIVE_QUESTS = 3

// ─── Quest Templates ────────────────────────────────────────────────────────

export const AVAILABLE_QUESTS: QuestTemplate[] = [
  // ── Study / IT ──
  {
    id: 'study-01',
    name: 'Viết Test Case',
    description: 'Viết test case đầy đủ cho một hàm TypeScript.',
    category: 'study',
    icon: 'lucide:flask-conical',
    baseExp: 30,
    baseGold: 12,
    baseDurationMinutes: 20,
    baseHpRestore: 5,
  },
  {
    id: 'study-02',
    name: 'Tối Ưu Truy Vấn SQL',
    description: 'Phân tích và tối ưu một câu truy vấn SQL chậm.',
    category: 'study',
    icon: 'lucide:database',
    baseExp: 35,
    baseGold: 14,
    baseDurationMinutes: 25,
    baseHpRestore: 5,
  },
  {
    id: 'study-03',
    name: 'Đọc Tài Liệu Kỹ Thuật',
    description: 'Đọc và ghi chú ít nhất 20 trang tài liệu kỹ thuật.',
    category: 'study',
    icon: 'lucide:book-open',
    baseExp: 20,
    baseGold: 8,
    baseDurationMinutes: 30,
    baseHpRestore: 8,
  },
  {
    id: 'study-04',
    name: 'Code Thuật Toán',
    description: 'Implement thuật toán sắp xếp hoặc tìm kiếm từ đầu.',
    category: 'study',
    icon: 'lucide:code-2',
    baseExp: 40,
    baseGold: 16,
    baseDurationMinutes: 30,
    baseHpRestore: 5,
  },
  {
    id: 'study-05',
    name: 'Học Lệnh Git Nâng Cao',
    description: 'Thực hành rebase, cherry-pick hoặc bisect.',
    category: 'study',
    icon: 'lucide:git-branch',
    baseExp: 25,
    baseGold: 10,
    baseDurationMinutes: 15,
    baseHpRestore: 5,
  },
  {
    id: 'study-06',
    name: 'Viết Documentation',
    description: 'Viết tài liệu đầy đủ cho một module hoặc API.',
    category: 'study',
    icon: 'lucide:file-text',
    baseExp: 22,
    baseGold: 9,
    baseDurationMinutes: 20,
    baseHpRestore: 5,
  },
  {
    id: 'study-07',
    name: 'Giải LeetCode',
    description: 'Hoàn thành một bài LeetCode Easy hoặc Medium.',
    category: 'study',
    icon: 'lucide:brain',
    baseExp: 45,
    baseGold: 18,
    baseDurationMinutes: 35,
    baseHpRestore: 6,
  },
  {
    id: 'study-08',
    name: 'Cấu Hình Workflow n8n',
    description: 'Tạo một automation workflow cơ bản trên n8n.',
    category: 'study',
    icon: 'lucide:workflow',
    baseExp: 35,
    baseGold: 14,
    baseDurationMinutes: 25,
    baseHpRestore: 5,
  },
  {
    id: 'study-09',
    name: 'Luyện Nghe Tiếng Anh',
    description: 'Luyện nghe thụ động tiếng Anh liên tục 20 phút.',
    category: 'study',
    icon: 'lucide:headphones',
    baseExp: 18,
    baseGold: 7,
    baseDurationMinutes: 20,
    baseHpRestore: 10,
  },
  {
    id: 'study-10',
    name: 'Xem Video Công Nghệ',
    description: 'Xem một video kỹ thuật chuyên sâu và ghi chép lại.',
    category: 'study',
    icon: 'lucide:monitor-play',
    baseExp: 15,
    baseGold: 6,
    baseDurationMinutes: 25,
    baseHpRestore: 8,
  },

  // ── Physical ──
  {
    id: 'phy-01',
    name: 'Hít Đất 20 Cái',
    description: 'Thực hiện 20 cái hít đất không nghỉ.',
    category: 'physical',
    icon: 'lucide:activity',
    baseExp: 20,
    baseGold: 8,
    baseDurationMinutes: 10,
    baseHpRestore: 15,
  },
  {
    id: 'phy-02',
    name: 'Plank 2 Phút',
    description: 'Duy trì tư thế plank liên tục 2 phút không nghỉ.',
    category: 'physical',
    icon: 'lucide:timer',
    baseExp: 25,
    baseGold: 10,
    baseDurationMinutes: 10,
    baseHpRestore: 12,
  },
  {
    id: 'phy-03',
    name: 'Vươn Vai & Đi Lại',
    description: 'Rời bàn làm việc, vươn vai và đi lại 10 phút.',
    category: 'physical',
    icon: 'lucide:person-standing',
    baseExp: 10,
    baseGold: 5,
    baseDurationMinutes: 10,
    baseHpRestore: 10,
  },
  {
    id: 'phy-04',
    name: 'Squat 30 Cái',
    description: 'Thực hiện 30 cái squat với kỹ thuật chuẩn.',
    category: 'physical',
    icon: 'lucide:zap',
    baseExp: 22,
    baseGold: 9,
    baseDurationMinutes: 12,
    baseHpRestore: 13,
  },
  {
    id: 'phy-05',
    name: 'Tập Cardio 15 Phút',
    description: 'Chạy bộ, nhảy dây hoặc cardio liên tục 15 phút.',
    category: 'physical',
    icon: 'lucide:heart-pulse',
    baseExp: 30,
    baseGold: 12,
    baseDurationMinutes: 20,
    baseHpRestore: 20,
  },
  {
    id: 'phy-06',
    name: 'Đi Bộ Nhanh 20 Phút',
    description: 'Đi bộ nhanh ngoài trời hoặc trên máy 20 phút.',
    category: 'physical',
    icon: 'lucide:footprints',
    baseExp: 18,
    baseGold: 7,
    baseDurationMinutes: 25,
    baseHpRestore: 15,
  },
  {
    id: 'phy-07',
    name: 'Kéo Giãn Cơ',
    description: 'Kéo giãn toàn thân với các bài tập yoga đơn giản 10 phút.',
    category: 'physical',
    icon: 'lucide:stretch-horizontal',
    baseExp: 12,
    baseGold: 5,
    baseDurationMinutes: 10,
    baseHpRestore: 18,
  },
  {
    id: 'phy-08',
    name: 'Push-up 3 Hiệp',
    description: 'Thực hiện 3 hiệp push-up (10 cái/hiệp), nghỉ 30 giây giữa hiệp.',
    category: 'physical',
    icon: 'lucide:dumbbell',
    baseExp: 28,
    baseGold: 11,
    baseDurationMinutes: 15,
    baseHpRestore: 14,
  },

  // ── Life / Chores ──
  {
    id: 'life-01',
    name: 'Quét & Lau Nhà',
    description: 'Quét và lau sạch toàn bộ sàn nhà.',
    category: 'life',
    icon: 'lucide:sparkles',
    baseExp: 20,
    baseGold: 8,
    baseDurationMinutes: 20,
    baseHpRestore: 6,
  },
  {
    id: 'life-02',
    name: 'Rửa Bát Ngay Sau Khi Ăn',
    description: 'Không để bát bẩn qua đêm, rửa liền sau bữa ăn.',
    category: 'life',
    icon: 'lucide:utensils',
    baseExp: 10,
    baseGold: 5,
    baseDurationMinutes: 10,
    baseHpRestore: 5,
  },
  {
    id: 'life-03',
    name: 'Sắp Xếp Góc Làm Việc',
    description: 'Dọn dẹp toàn bộ bàn làm việc, cắm sạc đúng chỗ.',
    category: 'life',
    icon: 'lucide:layout-dashboard',
    baseExp: 15,
    baseGold: 6,
    baseDurationMinutes: 15,
    baseHpRestore: 8,
  },
  {
    id: 'life-04',
    name: 'Vứt Rác Ra Ngoài',
    description: 'Thu gom và đem rác ra thùng rác ngoài đường.',
    category: 'life',
    icon: 'lucide:trash-2',
    baseExp: 8,
    baseGold: 4,
    baseDurationMinutes: 10,
    baseHpRestore: 4,
  },
  {
    id: 'life-05',
    name: 'Giặt Đồ & Phơi',
    description: 'Giặt máy một mẻ đồ và phơi cẩn thận.',
    category: 'life',
    icon: 'lucide:shirt',
    baseExp: 12,
    baseGold: 5,
    baseDurationMinutes: 15,
    baseHpRestore: 5,
  },
  {
    id: 'life-06',
    name: 'Lau Dọn Bàn Làm Việc',
    description: 'Lau sạch bàn, màn hình và bàn phím.',
    category: 'life',
    icon: 'lucide:monitor',
    baseExp: 10,
    baseGold: 4,
    baseDurationMinutes: 10,
    baseHpRestore: 6,
  },
  {
    id: 'life-07',
    name: 'Rửa Nhà Vệ Sinh',
    description: 'Vệ sinh sạch nhà tắm/nhà vệ sinh.',
    category: 'life',
    icon: 'lucide:droplets',
    baseExp: 25,
    baseGold: 10,
    baseDurationMinutes: 20,
    baseHpRestore: 5,
  },
  {
    id: 'life-08',
    name: 'Nấu Một Bữa Ăn',
    description: 'Tự nấu một bữa ăn đầy đủ dinh dưỡng.',
    category: 'life',
    icon: 'lucide:chef-hat',
    baseExp: 30,
    baseGold: 12,
    baseDurationMinutes: 40,
    baseHpRestore: 20,
  },

  // ── Mental Health ──
  {
    id: 'ment-01',
    name: 'Uống Đủ Nước',
    description: 'Uống ít nhất 2 lít nước trong ngày hôm nay.',
    category: 'mental',
    icon: 'lucide:glass-water',
    baseExp: 10,
    baseGold: 4,
    baseDurationMinutes: 480,
    baseHpRestore: 15,
  },
  {
    id: 'ment-02',
    name: 'Nhắm Mắt Nghỉ Ngơi',
    description: 'Nhắm mắt thư giãn hoàn toàn trong 5 phút.',
    category: 'mental',
    icon: 'lucide:eye-off',
    baseExp: 8,
    baseGold: 4,
    baseDurationMinutes: 5,
    baseHpRestore: 20,
  },
  {
    id: 'ment-03',
    name: 'Detox Điện Thoại',
    description: 'Không chạm vào điện thoại liên tục trong 30 phút.',
    category: 'mental',
    icon: 'lucide:smartphone-nfc',
    baseExp: 20,
    baseGold: 8,
    baseDurationMinutes: 30,
    baseHpRestore: 25,
  },
  {
    id: 'ment-04',
    name: 'Viết Nhật Ký',
    description: 'Viết nhật ký tâm trạng và suy nghĩ trong ngày.',
    category: 'mental',
    icon: 'lucide:pen-line',
    baseExp: 12,
    baseGold: 5,
    baseDurationMinutes: 10,
    baseHpRestore: 15,
  },
  {
    id: 'ment-05',
    name: 'Thiền Định 10 Phút',
    description: 'Ngồi yên, hít thở sâu và thiền định trong 10 phút.',
    category: 'mental',
    icon: 'lucide:sparkles',
    baseExp: 18,
    baseGold: 7,
    baseDurationMinutes: 10,
    baseHpRestore: 30,
  },
  {
    id: 'ment-06',
    name: 'Ngủ Đúng Giờ',
    description: 'Lên giường trước 23:00 và không dùng điện thoại sau 22:30.',
    category: 'mental',
    icon: 'lucide:moon',
    baseExp: 25,
    baseGold: 10,
    baseDurationMinutes: 30,
    baseHpRestore: 40,
  },
  {
    id: 'ment-07',
    name: 'Đọc Sách 20 Phút',
    description: 'Đọc sách giấy hoặc ebook, không dùng mạng xã hội.',
    category: 'mental',
    icon: 'lucide:library',
    baseExp: 20,
    baseGold: 8,
    baseDurationMinutes: 20,
    baseHpRestore: 12,
  },

  // ── Social ──
  {
    id: 'soc-01',
    name: 'Hỏi Thăm Bạn Bè',
    description: 'Nhắn tin hỏi thăm một người bạn chưa liên hệ lâu.',
    category: 'social',
    icon: 'lucide:message-circle',
    baseExp: 12,
    baseGold: 5,
    baseDurationMinutes: 10,
    baseHpRestore: 10,
  },
  {
    id: 'soc-02',
    name: 'Gọi Điện Cho Gia Đình',
    description: 'Gọi điện video hoặc thoại cho bố mẹ hoặc anh/chị em.',
    category: 'social',
    icon: 'lucide:phone-call',
    baseExp: 20,
    baseGold: 8,
    baseDurationMinutes: 20,
    baseHpRestore: 20,
  },
  {
    id: 'soc-03',
    name: 'Gặp Mặt 5 Người',
    description: 'Giao tiếp trực tiếp và nói chuyện với ít nhất 5 người.',
    category: 'social',
    icon: 'lucide:users',
    baseExp: 30,
    baseGold: 12,
    baseDurationMinutes: 60,
    baseHpRestore: 15,
  },
  {
    id: 'soc-04',
    name: 'Review Code Người Khác',
    description: 'Đọc và review code/PR cho đồng nghiệp hoặc bạn bè.',
    category: 'social',
    icon: 'lucide:git-pull-request',
    baseExp: 28,
    baseGold: 11,
    baseDurationMinutes: 20,
    baseHpRestore: 8,
  },
  {
    id: 'soc-05',
    name: 'Chia Sẻ Điều Tích Cực',
    description: 'Đăng/chia sẻ nội dung tích cực, hữu ích lên mạng xã hội.',
    category: 'social',
    icon: 'lucide:share-2',
    baseExp: 10,
    baseGold: 5,
    baseDurationMinutes: 10,
    baseHpRestore: 8,
  },
  {
    id: 'soc-06',
    name: 'Học Từ Người Khác',
    description: 'Chủ động hỏi và học một điều mới từ người xung quanh.',
    category: 'social',
    icon: 'lucide:lightbulb',
    baseExp: 20,
    baseGold: 8,
    baseDurationMinutes: 30,
    baseHpRestore: 10,
  },

  // ── Creative / Adventure ──
  {
    id: 'cre-01',
    name: 'Vẽ Một Bức Tranh',
    description: 'Vẽ bất kỳ thứ gì, dù đơn giản — quan trọng là sáng tạo.',
    category: 'creative',
    icon: 'lucide:paintbrush',
    baseExp: 22,
    baseGold: 9,
    baseDurationMinutes: 30,
    baseHpRestore: 12,
  },
  {
    id: 'cre-02',
    name: 'Viết Thơ Hoặc Truyện',
    description: 'Viết một đoạn thơ ngắn hoặc truyện ngắn tự sáng tác.',
    category: 'creative',
    icon: 'lucide:feather',
    baseExp: 20,
    baseGold: 8,
    baseDurationMinutes: 20,
    baseHpRestore: 10,
  },
  {
    id: 'cre-03',
    name: 'Chụp Ảnh Nghệ Thuật',
    description: 'Chụp một bức ảnh đẹp và ý nghĩa về cuộc sống xung quanh.',
    category: 'creative',
    icon: 'lucide:camera',
    baseExp: 15,
    baseGold: 6,
    baseDurationMinutes: 15,
    baseHpRestore: 8,
  },
  {
    id: 'cre-04',
    name: 'Nấu Thử Món Mới',
    description: 'Tìm công thức và nấu thử một món ăn chưa từng nấu bao giờ.',
    category: 'creative',
    icon: 'lucide:soup',
    baseExp: 30,
    baseGold: 12,
    baseDurationMinutes: 60,
    baseHpRestore: 25,
  },
  {
    id: 'cre-05',
    name: 'Đi Tìm Một Con Mèo',
    description: 'Ra ngoài tìm và vuốt ve một chú mèo hoang. Nhiệm vụ khó — mèo tự do!',
    category: 'creative',
    icon: 'lucide:cat',
    baseExp: 35,
    baseGold: 15,
    baseDurationMinutes: 30,
    baseHpRestore: 30,
  },
  {
    id: 'cre-06',
    name: 'Ngắm Hoàng Hôn / Bình Minh',
    description: 'Ra ngoài trời và ngắm hoàng hôn hoặc bình minh trọn vẹn.',
    category: 'creative',
    icon: 'lucide:sunrise',
    baseExp: 25,
    baseGold: 10,
    baseDurationMinutes: 30,
    baseHpRestore: 35,
  },
]

// ─── Rarity Config ───────────────────────────────────────────────────────────

export const RARITIES: Rarity[] = ['white', 'blue', 'purple', 'gold']

export const RARITY_CONFIG: Record<Rarity, RarityConfig> = {
  white: {
    label: 'Thường',
    weight: 60,
    expMult: 1,
    goldMult: 1,
    timeMult: 1,
    hpRestoreMult: 1,
    borderClass: 'border-border-default',
    bgClass: 'bg-bg-surface',
    textClass: 'text-text-secondary',
    badgeClass: 'bg-bg-elevated text-text-dim',
    shadowClass: '',
    pinClass: 'bg-text-dim',
  },
  blue: {
    label: 'Hiếm',
    weight: 25,
    expMult: 1.5,
    goldMult: 1.5,
    timeMult: 1.5,
    hpRestoreMult: 1.3,
    borderClass: 'border-accent-sky',
    bgClass: 'bg-accent-sky/5',
    textClass: 'text-accent-sky',
    badgeClass: 'bg-accent-sky/20 text-accent-sky',
    shadowClass: 'shadow-accent-sky/20',
    pinClass: 'bg-accent-sky',
  },
  purple: {
    label: 'Sử Thi',
    weight: 10,
    expMult: 2.5,
    goldMult: 2,
    timeMult: 2,
    hpRestoreMult: 1.6,
    borderClass: 'border-violet-500',
    bgClass: 'bg-violet-500/5',
    textClass: 'text-violet-400',
    badgeClass: 'bg-violet-500/20 text-violet-400',
    shadowClass: 'shadow-violet-500/20',
    pinClass: 'bg-violet-400',
  },
  gold: {
    label: 'Huyền Thoại',
    weight: 5,
    expMult: 4,
    goldMult: 3,
    timeMult: 5,
    hpRestoreMult: 2.5,
    borderClass: 'border-accent-amber',
    bgClass: 'bg-accent-amber/5',
    textClass: 'text-accent-amber',
    badgeClass: 'bg-accent-amber/20 text-accent-amber',
    shadowClass: 'shadow-accent-amber/20',
    pinClass: 'bg-accent-amber',
  },
}

// ─── Rank Config ─────────────────────────────────────────────────────────────

export const RANKS: Rank[] = ['F', 'E', 'D', 'C', 'B', 'A', 'S', 'SS']

export const RANK_CONFIG: RankConfig[] = [
  { label: 'F', minExp: 0, nextExp: 100, title: 'Lính Mới' },
  { label: 'E', minExp: 100, nextExp: 300, title: 'Chiến Binh' },
  { label: 'D', minExp: 300, nextExp: 700, title: 'Kiếm Sĩ' },
  { label: 'C', minExp: 700, nextExp: 1500, title: 'Dũng Sĩ' },
  { label: 'B', minExp: 1500, nextExp: 3000, title: 'Hiệp Sĩ' },
  { label: 'A', minExp: 3000, nextExp: 6000, title: 'Đại Hiệp' },
  { label: 'S', minExp: 6000, nextExp: 12000, title: 'Huyền Thoại' },
  { label: 'SS', minExp: 12000, nextExp: null, title: 'Bất Tử' },
]

// ─── Category Labels ──────────────────────────────────────────────────────────

export const CATEGORY_CONFIG = {
  study: { label: 'Học Tập / IT', icon: 'lucide:book-open', color: 'text-accent-sky' },
  physical: { label: 'Thể Chất', icon: 'lucide:dumbbell', color: 'text-accent-coral' },
  life: { label: 'Đời Sống', icon: 'lucide:home', color: 'text-accent-amber' },
  mental: { label: 'Tinh Thần', icon: 'lucide:heart', color: 'text-violet-400' },
  social: { label: 'Giao Tiếp', icon: 'lucide:users', color: 'text-green-400' },
  creative: { label: 'Sáng Tạo', icon: 'lucide:palette', color: 'text-rose-400' },
}

// ─── Shop Items ───────────────────────────────────────────────────────────────

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'hp_potion',
    name: 'Bình Máu Nhỏ',
    description: 'Hồi phục 30 HP (không vượt quá máu tối đa).',
    price: 20,
    icon: 'lucide:heart-handshake',
    effect: 'hp_potion',
  },
  {
    id: 'exp_scroll',
    name: 'Cuộn Giấy Thông Thái',
    description: 'Nhân đôi EXP nhận được cho 3 nhiệm vụ tiếp theo.',
    price: 50,
    icon: 'lucide:scroll-text',
    effect: 'exp_scroll',
  },
  {
    id: 'dragon_heart',
    name: 'Trái Tim Rồng',
    description: 'Tăng vĩnh viễn Máu Tối Đa +20 và hồi đầy máu.',
    price: 200,
    icon: 'lucide:gem',
    effect: 'dragon_heart',
  },
]
